### ISSUE TITLE
Unable to access repository

### ISSUE THREAD

**Issue by JonFear** [llopisdon/skies-adsb#1]
Problem, any thoughts?

Cloning into ‘skies-adsb’…
[git@github.com](mailto:git@github.com): Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by thebaldgeek** [comment]
If your intent is to clone-only a repo, use HTTPS URL ([https://github.com/{user_name}/{project_name}.git](https://github.com/%7Buser_name%7D/%7Bproject_name%7D.git)) instead of SSH URL (git@github.com:{user_name}/{project_name}.git), which avoids (unnecessary) public key validation.

**Comment by machineinteractive** [comment]
> Problem, any thoughts?
> 
> Cloning into ‘skies-adsb’… [git@github.com](mailto:git@github.com): Permission denied (publickey). fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.

hi @JonFear as @thebaldgeek mentioned if your intent is to make a local copy then
use the https url to clone the project:

https://github.com/llopisdon/skies-adsb.git

If you wish to submit new maps or submit bug fixes etc.. please fork the project and submit any changes or updates via a pull request.

thanks
Don
